test_p1 (__main__.Test.test_p1) ... ok
test_p10 (__main__.Test.test_p10) ... ok
test_p2 (__main__.Test.test_p2) ... ERROR
test_p3 (__main__.Test.test_p3) ... ok
test_p4 (__main__.Test.test_p4) ... ok
test_p5 (__main__.Test.test_p5) ... ERROR
test_p6 (__main__.Test.test_p6) ... ok
test_p7 (__main__.Test.test_p7) ... ok
test_p8 (__main__.Test.test_p8) ... ERROR
test_p9 (__main__.Test.test_p9) ... ERROR

======================================================================
ERROR: test_p2 (__main__.Test.test_p2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\prg-basics\13-Test3\results\grade-test3-ZIISS1-1112.py", line 18, in test_p2
    self.assertEqual(p2.f("11 9 + 15 - 14 +"),19)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Studia\prg-basics\13-Test3\results\p2.py", line 8, in f
    queue1.put(char)
TypeError: Queue.put() missing 1 required positional argument: 'item'

======================================================================
ERROR: test_p5 (__main__.Test.test_p5)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\prg-basics\13-Test3\results\grade-test3-ZIISS1-1112.py", line 36, in test_p5
    stadium.m1("S",20)
  File "c:\Studia\prg-basics\13-Test3\results\p5.py", line 6, in m1
    for key in self.stadion.keys():
               ^^^^^^^^^^^^^^^^^^^
RuntimeError: dictionary changed size during iteration

======================================================================
ERROR: test_p8 (__main__.Test.test_p8)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\prg-basics\13-Test3\results\grade-test3-ZIISS1-1112.py", line 51, in test_p8
    import p8
ModuleNotFoundError: No module named 'p8'

======================================================================
ERROR: test_p9 (__main__.Test.test_p9)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Studia\prg-basics\13-Test3\results\grade-test3-ZIISS1-1112.py", line 56, in test_p9
    import p9
ModuleNotFoundError: No module named 'p9'

----------------------------------------------------------------------
Ran 10 tests in 0.027s

FAILED (errors=4)
